### PR TITLE
Adding devcontainer for codespaces

### PR DESCRIPTION
**Pull request by Rhynorater**
Adding codespaces that makes dev super easy. Will provide Loom video on usage shortly.

### CODE REVIEW

**Review by Sytten — APPROVED** [review]

**Comment by Sytten** [comment]
Can we make it so it install mdbook automatically?

**Comment by Rhynorater** [comment]
It already does @Sytten

**Comment by Rhynorater** [comment]
https://www.loom.com/share/0453dc2aa0bc42df9790c3bb882df48d

**Comment by Rhynorater** [comment]
Dont merge this yet, I'm gonna go ahead and make another change to the README explaining how this works.

**Comment by Rhynorater** [comment]
Ok second thought: I'm gonna merge and modify readme later so Ninjeeter can use it.

**Pull request merged**
